name: Smart Contract CI

on:
  push:
    branches:
      - main
      - ui-change
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Tenderly CLI
        run: curl https://raw.githubusercontent.com/Tenderly/tenderly-cli/master/scripts/install-linux.sh | sudo sh

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Hardhat dependencies
        run: npm install
        working-directory: packages/hardhat-2.14

      # - name: Run Hardhat tests
      #   run: npm run test:devnet
      #   working-directory: packages/hardhat-2.14
      #   env:
      #     TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_TOKEN }}
      #     TENDERLY_PROJECT_SLUG: mini-safe # your project slug
      #     TENDERLY_DEVNET_TEMPLATE: mini-safe-tests # your devnet template slug
      #     TENDERLY_ACCOUNT_ID: nenad # your username or organization name

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: packages/frontend

      - name: Playwright setup
        run: npx playwright install
        working-directory: packages/frontend

      # - name: Create a DevNet for E2E tests and stage the contracts
      #   run: npm run stage
      #   working-directory: packages/hardhat-2.14
      #   env:
      #     TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_TOKEN }}
      #     TENDERLY_PROJECT_SLUG: mini-safe # your project slug
      #     TENDERLY_DEVNET_TEMPLATE: mini-safe-tests # your devnet template slug
      #     TENDERLY_ACCOUNT_ID: nenad # your username or organization name

      - name: Run E2E Tests
        run: cd ../hardhat-2.14 && npm run stage && cd ../frontend && npm run test:headless
        working-directory: packages/frontend
        env:
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_TOKEN }}
          TENDERLY_PROJECT_SLUG: mini-safe # your project slug
          TENDERLY_DEVNET_TEMPLATE: mini-safe-tests # your devnet template slug
          TENDERLY_ACCOUNT_ID: nenad # your username or organization name

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/frontend/playwright-report/
          retention-days: 30